# Generated by Django 4.2.4 on 2023-08-16 08:47

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('birth_country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('ISBN', models.CharField(max_length=20)),
                ('Genres', models.CharField(choices=[('biography', 'Biography'), ('science', 'Science'), ('business', 'Business'), ('history', 'History'), ('romance', 'Romance'), ('fiction', 'Fiction'), ('fantasy', 'Fantasy'), ('poetry', 'Poetry'), ('science fiction', 'Science Fiction'), ('novel', 'Novel'), ('psychology', 'Psychology'), ('self help', 'Self Help'), ("children's'", "Children's'")])),
                ('release_data', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LibManager.author')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('membership_type', models.CharField(choices=[('vip', 'VIP'), ('normal', 'Normal')])),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_start_data', models.DateField(auto_now_add=True)),
                ('reserve_end', models.DateField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LibManager.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LibManager.users')),
            ],
        ),
    ]
