# Generated by Django 4.2.4 on 2023-08-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibManager', '0002_rename_release_data_book_publication_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_image',
            field=models.ImageField(default='', upload_to='book images'),
        ),
    ]
