# Generated by Django 4.2.4 on 2023-08-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibManager', '0004_alter_users_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='cost',
            field=models.IntegerField(null=True),
        ),
    ]
